# alias envsubst='/usr/local/opt/gettext/bin/envsubst'
alias updatedb='sudo launchctl load -w /System/Library/LaunchDaemons/com.apple.locate.plist'
alias pes='pipenv shell'
alias auto_comp_kubelet='source <(kubectl completion zsh)'
alias kuberun='kubectl run --rm -it $(date +%s) --image'
alias kube-ops-view='docker run -it -p 8080:8080 -e CLUSTERS=http://docker.for.mac.localhost:8001 hjacobs/kube-ops-view'
alias ks-avp-dev='/opt/homebrew/bin/kustomize build --load-restrictor=LoadRestrictionsNone --enable-alpha-plugins . | argocd-vault-plugin generate -c ~/.argo/avp_dev.yaml -'
alias ks-avp-qa='/opt/homebrew/bin/kustomize build --load-restrictor=LoadRestrictionsNone --enable-alpha-plugins . | argocd-vault-plugin generate -c ~/.argo/avp_qa.yaml -'
alias ks-avp-uat='/opt/homebrew/bin/kustomize build --load-restrictor=LoadRestrictionsNone --enable-alpha-plugins . | argocd-vault-plugin generate -c ~/.argo/avp_uat.yaml -'
alias ks-avp-prod='/opt/homebrew/bin/kustomize build --load-restrictor=LoadRestrictionsNone --enable-alpha-plugins . | argocd-vault-plugin generate -c ~/.argo/avp_prod.yaml -'